FROM clearwater/base
MAINTAINER maintainers@projectclearwater.org

RUN apt-get install -y --force-yes clearwater-sip-stress-coreonly
RUN apt-get install -y --force-yes clearwater-sip-stress

EXPOSE 5052 5054